### ISSUE TITLE
No .jar file included

### ISSUE THREAD

**Issue by jurgenvisser** [HybridDog/cave_lighting#1]
Hello HybridDog,

I want to use your mod as it seems quite useful in my server but I don't seem to be able to install it on my client side Minecraft folder. I only know of installing mods as .jar files and you mod doesn't include one. Are you able to push a .jar file in the repo so I can use it? that would be helpful

greetings Jurgen Visser
feel free to contact me (jurgenbv@gmail.com)
others... please don't if you find this.

**Comment by HybridDog** [comment]
The mod works with [Minetest](https://www.minetest.net/), so it's incompatible with Minecraft.
